FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY src/ ./

RUN mkdir -p /root/.nuget/NuGet
COPY ./config/NuGetPackageSource.Config /root/.nuget/NuGet/NuGet.Config

RUN dotnet build NotificationHost/NotificationHost.csproj -o notification-query

FROM build AS publish
WORKDIR /app

RUN dotnet publish -c Release -o dist/notification-query NotificationHost/NotificationHost.csproj

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

COPY --from=publish /app/dist ./

EXPOSE 80
EXPOSE 8080

ENV ASPNETCORE_ENVIRONMENT develop

ENTRYPOINT ["dotnet", "notification-query/ShipService.External.NotificationHost.dll"]