version: '3'
services:
  command_web_host:
    image: ship/command_web_host
    build:
      context: .
      dockerfile: Dockerfile-Web
    container_name: command_web_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8085:80
  command_worker_host:
    image: ship/command_worker_host
    build:
      context: .
      dockerfile: Dockerfile-Worker
    container_name: command_worker_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8086:80
  event_worker_host:
    image: ship/event_worker_host
    build:
      context: .
      dockerfile: Dockerfile-Event
    container_name: event_worker_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8087:80
    volumes:
      - type: volume
        source: ship-data-volume
        target: /app/db/ship-service
  authentication_query_host:
    image: ship/authentication_query_host
    build:
      context: .
      dockerfile: Dockerfile-AuthQuery
    container_name: authentication_query_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8088:80
  ship_query_host:
    image: ship/ship_query_host
    build:
      context: .
      dockerfile: Dockerfile-ShipQuery
    container_name: ship_query_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8089:80
    volumes:
      - type: volume
        source: ship-data-volume
        target: /app/db/ship-service    
  notification_host:
    image: ship/notification_host
    build:
      context: .
      dockerfile: Dockerfile-Notification
    container_name: notification_host
    networks:  
      - ship-net
    ports:
      - 127.0.0.40:8090:80
      - 127.0.0.40:8091:8080
networks:
  ship-net:
    driver: "bridge"
volumes:
  ship-data-volume:

