// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipService.External.NotificationHost.Repository;

namespace ShipService.External.NotificationHost.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20210827101235_Update constructor")]
    partial class Updateconstructor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ShipService.External.NotificationHost.Models.NotificationClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ClientId");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CorrelationId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsMarkedToDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsMarkedToDelete");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("RolesAllowedToRead")
                        .HasColumnType("TEXT")
                        .HasColumnName("RolesAllowedToRead");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("NotificationClients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43d1f414-64bf-4418-a8f0-da2731df799b"),
                            ClientId = "abcd",
                            CorrelationId = new Guid("82bd1940-564d-4cbf-9335-d61ae6280505"),
                            CreatedBy = new Guid("001b42f5-18a7-480c-b41c-5c21082b20ec"),
                            CreatedDate = new DateTime(2021, 8, 27, 10, 12, 35, 265, DateTimeKind.Utc).AddTicks(2893),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("adc344cf-e155-471d-beb2-f49412ee52ab"),
                            LastUpdatedDate = new DateTime(2021, 8, 27, 10, 12, 35, 265, DateTimeKind.Utc).AddTicks(2909),
                            RolesAllowedToRead = "",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
