// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipService.External.NotificationHost.Repository;

namespace ShipService.External.NotificationHost.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20210827091041_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ShipService.External.NotificationHost.Models.NotificationClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ClientId");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CorrelationId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsMarkedToDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsMarkedToDelete");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("RolesAllowedToRead")
                        .HasColumnType("TEXT")
                        .HasColumnName("RolesAllowedToRead");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("NotificationClients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07226db8-e7c3-423d-980b-63c7795f89f5"),
                            ClientId = "abcd",
                            CorrelationId = new Guid("87238a3f-4a0b-4d39-9f78-40bb34e345d1"),
                            CreatedBy = new Guid("b2b8527c-d62d-4e03-bb23-21bb20d43a36"),
                            CreatedDate = new DateTime(2021, 8, 27, 9, 10, 40, 872, DateTimeKind.Utc).AddTicks(5449),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("ae567feb-f008-4055-bf46-4767090ef661"),
                            LastUpdatedDate = new DateTime(2021, 8, 27, 9, 10, 40, 872, DateTimeKind.Utc).AddTicks(5463),
                            RolesAllowedToRead = "",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
