// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipService.External.Infrastructure.Authentication.Cqrs.Repository.Sqlite;

namespace ShipService.External.Infrastructure.Authentication.Cqrs.Repository.Sqlite.Migrations
{
    [DbContext(typeof(AuthenticationViewModelDbContext))]
    [Migration("20210825193507_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ShipService.External.AuthViewModel.AuthenticationViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsMarkedToDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsMarkedToDelete");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.Property<string>("RolesAllowedToRead")
                        .HasColumnType("TEXT")
                        .HasColumnName("RolesAllowedToRead");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationViewModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b03bfb27-3bfb-4457-b0d8-f1c4675a4862"),
                            CreatedBy = new Guid("c780c7bc-c02f-4386-85fb-d954f56ef048"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 538, DateTimeKind.Utc).AddTicks(9639),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("dc934453-c9d4-4880-8af3-8f8951cbc75b"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 538, DateTimeKind.Utc).AddTicks(9652),
                            Password = "Abc123",
                            Role = "Admin",
                            RolesAllowedToRead = "",
                            Username = "test_admin1@yopmail.com",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0799cc7f-4df9-48a8-910d-097750ae51ac"),
                            CreatedBy = new Guid("a9778730-5e11-4697-a8b6-a7fb8f61f243"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6724),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("f3ac08ae-86e3-40b8-b884-b2373072f30b"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6730),
                            Password = "Abc123",
                            Role = "Admin",
                            RolesAllowedToRead = "",
                            Username = "test_admin2@yopmail.com",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ef15d4ba-5672-490f-8159-5917bebac241"),
                            CreatedBy = new Guid("1104fc0a-ded8-482e-b68e-155558dd3174"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6875),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("af4f0f74-d5e6-4c74-87f9-9bff8bb2167b"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6878),
                            Password = "Abc123",
                            Role = "User",
                            RolesAllowedToRead = "",
                            Username = "test_user1@yopmail.com",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ae014d45-f533-4618-b092-32fec0a3d5eb"),
                            CreatedBy = new Guid("e027ae6e-55eb-435c-831d-d0e42ee599bc"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6902),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("e132c05b-a1e7-422a-8bb1-f7bf811c66f0"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6904),
                            Password = "Abc123",
                            Role = "User",
                            RolesAllowedToRead = "",
                            Username = "test_user2@yopmail.com",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7b2cfc7a-a17d-48f5-92f9-16b4b26ae10f"),
                            CreatedBy = new Guid("67a8c346-df6f-41f3-aaad-70c86916812a"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6923),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("bf255083-5dc5-4ad3-af16-3119b715e502"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6930),
                            Password = "Abc123",
                            Role = "Anonymous",
                            RolesAllowedToRead = "",
                            Username = "test_anon1@yopmail.com",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a610c2c1-400d-4742-b1d8-58122f66c044"),
                            CreatedBy = new Guid("06dd95c3-b348-4e34-970f-0cc26d412eaa"),
                            CreatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6959),
                            IsMarkedToDelete = false,
                            LastUpdatedBy = new Guid("87cfd8a5-b96b-4799-80c7-236b2f9268fa"),
                            LastUpdatedDate = new DateTime(2021, 8, 25, 19, 35, 6, 540, DateTimeKind.Utc).AddTicks(6961),
                            Password = "Abc123",
                            Role = "Anonymous",
                            RolesAllowedToRead = "",
                            Username = "test_anon2@yopmail.com",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
